import { ArrowDown, ArrowUp, BarChart3, FileCode2, ImagePlus, List, ListOrdered, MoreHorizontal, Plus, Quote, Table2, Trash2 } from 'lucide-react'
import { sectionHeading } from '../../utils/sectionLabels'
import EditableContent from './EditableContent'
import ElementEditor from './ElementEditor'

const elementMenuItems = [
  ['paragraph', 'Paragraph', FileCode2], ['heading', 'Heading / Subsection', Quote], ['bullet-list', 'Bullet List', List], ['numbered-list', 'Numbered List', ListOrdered], ['figure', 'Figure', ImagePlus], ['table', 'Table', Table2], ['chart', 'Chart', BarChart3], ['equation', 'Equation', FileCode2], ['quote', 'Quote', Quote], ['code', 'Code Block', FileCode2],
]

export default function SectionCard({ section, path, selected, onSelect, onUpdate, onUpdateTitle, onAddElement, onUpdateElement, onDeleteElement, onDuplicateElement, onMoveElement, onMoveSection, onDeleteSection, onAddSubsection, numbering }) {
  const heading = sectionHeading(section, path)
  const hasContent = Boolean(section.content?.trim() || section.elements?.length || section.children?.length)
  const removeSection = () => { if (!hasContent || window.confirm(`Delete “${section.title}” and its content? This cannot be undone.`)) onDeleteSection(section.id) }
  return <section id={section.id} className={`section-card section-card--level-${path.length} ${selected ? 'is-selected' : ''}`} onClick={() => onSelect(section.id)}><div className="section-card-heading"><input value={heading} onChange={(event) => onUpdateTitle(section.id, event.target.value.replace(/^([IVXLCDM]+\.|[A-Z]\.)\s*/, ''))} aria-label="Section title" /><div className="section-actions"><button type="button" className="icon-button" title="Move up" onClick={() => onMoveSection(section.id, -1)} aria-label="Move section up"><ArrowUp size={15} /></button><button type="button" className="icon-button" title="Move down" onClick={() => onMoveSection(section.id, 1)} aria-label="Move section down"><ArrowDown size={15} /></button>{path.length === 1 && <button type="button" className="icon-button" title="Add subsection" onClick={() => onAddSubsection(section.id)} aria-label="Add subsection"><Plus size={15} /></button>}<button type="button" className="icon-button" title="Delete section" onClick={removeSection} aria-label={`Delete ${section.title}`}><Trash2 size={15} /></button><MoreHorizontal className="section-actions-more" size={17} aria-hidden="true" /></div></div><EditableContent value={section.content} onChange={(value) => onUpdate(section.id, value)} placeholder={`Write the ${section.title.toLowerCase()} here...`} />{section.elements?.map((element) => <ElementEditor key={element.id} element={element} number={numbering[element.id]?.value} onChange={(update) => onUpdateElement(section.id, element.id, update)} onDelete={() => onDeleteElement(section.id, element.id)} onDuplicate={() => onDuplicateElement(section.id, element.id)} onMove={(direction) => onMoveElement(section.id, element.id, direction)} />)}<details className="add-element-menu" onClick={(event) => event.stopPropagation()}><summary className="add-element"><Plus size={15} aria-hidden="true" /> Add element</summary><div className="element-popover">{elementMenuItems.map(([type, label, Icon]) => <button type="button" key={type} onClick={() => onAddElement(section.id, type)}><Icon size={15} /><span>{label}</span></button>)}</div></details></section>
}
